import type {Metadata} from "next";
import {Inter} from "next/font/google";
import localFont from "next/font/local";
import Head from "next/head";
import Meta from "../components/meta";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

const light = localFont({
    src: [
        {path: './light.ttf'},
        {path: './medium.ttf'},
        {path: './texter.ttf'},
    ]
})

export const metadata: Metadata = {
    title: "Candy Party Bus",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en">
            <Head>
                <Meta/>
            </Head>
            <body className={light.className}>{children}</body>
            </html>
        </>
    );
}
